export {default as hero} from "./hero.png"
export { default as logo } from "./ubc-logo.png"
export { default as iloApproved } from "./ilo-approved.png"
export { default as greenKiln } from "./green-kiln.png"
export { default as awal } from "./awal.png"
export { default as laalAwal } from "./laal-awal.png"
export { default as bahriaTown } from "./bahria.png"
export { default as lums } from "./lums.png"
export { default as metro } from "./metro.png"
export { default as placeholder } from "./placeholder.png"
export { default as bahriaGrandMosque } from "./bahria-grand-mosque.png"
export { default as liberty } from "./liberty.png"
export { default as soeLums } from "./soe-lums.png"
export { default as coloredLogo} from "./ubc-colored.png"

